version: "3.9"
services:
    db:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=task-db
            - MYSQL_USER=task-service
            - MYSQL_PASSWORD=password
        volumes:
            - db-data:/var/lib/mysql
        container_name: mysql1
    web:
        image: syd.ocir.io/sdvw2vh5qake/task-manager/service:1.0
        ports:
            - "8080:8080"
        restart: always
        links:
            - db
        depends_on:
            - "db"
        container_name: task-service
    client:
        image: syd.ocir.io/sdvw2vh5qake/task-manager/client:1.0
        ports:
            - "80:80"
        restart: always
        depends_on:
            - "web"
        container_name: task-client
volumes:
    db-data:
